---
- hosts: all

  vars:
    app_name: opencoindata 
    app_dir: /root/.go/github.com/lox/{{ app_name }}

  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      sudo: yes

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - golang
        - rsync
        - wget
        - unattended-upgrades
        - supervisor
        - screen
        - git-core
        - mysql-server
        - build-essential

    - name: create go workspace dirs
      action: file path={{ app_dir }} state=directory

    - name: update codebase on server
      synchronize: src=../ dest={{ app_dir }} rsync_timeout=45

    - name: symlink app into homedir
      action: file src={{ app_dir }} dest=/root/{{ app_name }} state=link
    
    - name: build app binary
      command: GOPATH=/root/.go GOBIN=/root/.go/bin make chdir={{ app_dir }}  

    - name: create supervisor program config
      action: template src=./supervisor.conf dest=/etc/supervisor/conf.d/{{ app_name }}.conf
      notify:
        - reload supervisor

  handlers:
    - name: reload supervisor
      action: supervisorctl name={{ app_name }} state=restarted










